name: LocalChat
main: DataLion\LocalChat\Main
version: 0.0.1
api: 5.14.1
author: DataLion
description: LocalChat plugin
permissions:
    lc.command:
      description: "LocalChat Main command"
      default: op
    lc.command.toggle:
      description: "Toggle localchat"
      default: op
    lc.command.setradius:
      description: "Change Chat radius"
      default: op
